### PR TITLE
Feature/tenant mgmt

### PR DESCRIPTION
**Pull request by justinfinch**
Got the basics entities create and db migrations in place.  I had to make some changes to infrastructure projects so wanted to get that merged in even though this ins't complete yet.  Take a look and let me know if I am on the right track.

### CODE REVIEW

**Comment by mmalik76** [comment]
Looks like you figured out how to use the ValueObject, cool. One thing I would recommend would be to use the ColumnAttribute instead of the FireDepartmentTypeConfiguration, that way all of logic is in one place. It might not be 100% necessary, but I think Dtos should have the Serializable attribute.

**Comment by mmalik76** [comment]
At some point I would also like to pick you brain on the use of managers and come up with a general rule of thumb. This was one thing I struggled with. I think putting the Create logic in there makes total sense, but we might be limiting ourselves by no going straight to Repository for Gets & GetLists, just a thought.

**Comment by justinfinch** [comment]
Sounds good on the column attribute, although not sure how do do that with a value object.  I'll give it a shot though.

This was what I was going by for what goes in app service vs domain service:


> We can simply say that it's not application service task. Because it's not a use-case, instead, it's a business operation. We may use same 'assign a task to a user' domain logic in a different use-case. Say that we may have another screen to somehow update the task and this updating can include assigning the task to another person. So, we can use same domain logic there. Also, we may have 2 different UI (one mobile application and one web application) that shares same domain or we may have a web API for remote clients that includes a task assign operation.

We may be able to use Specifications to help with the query side of things:

http://www.aspnetboilerplate.com/Pages/Documents/Specifications

**Comment by justinfinch** [comment]
Also can you approve the pull request following these instructions.

https://help.github.com/articles/approving-a-pull-request-with-required-reviews/

Next time I'll do smaller changes.

**Review by mmalik76 — APPROVED** [review]

**Pull request merged**
